### ISSUE TITLE
Recieve invalid_external_user_ids while app is still opening

### ISSUE THREAD

**Issue by iojOMlyzI06b8nWnWfxI1BW** [OneSignal/api#27]
### What happened?

So I open my app and leave it 10 minutes
The screen is still on and the app is opening
I post a notification using postman and recieve invalid_external_user_ids
The app still recieved my message after that

### Steps to reproduce?

```Markdown
1. Add react-native-onesignal to the app
2. Add OneSignal.setExternalUserId("123456789");
3. Open the app
4. Leave the phone there for 10 minutes. The phone wasn't turn off because it was connect to PC using USB cable
5. Post notification to Onesignal (123456789)
6. Recieve invalid_external_user_ids
7. The app recieve the message
```

### What did you expect to happen?

The phone is on. The app is still opening. The api should return no errors

### React Native OneSignal SDK version

4.5.0

### Which platform(s) are affected?

- [ ] iOS
- [X] Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jkasten2** [comment]
@iojOMlyzI06b8nWnWfxI1BW Thanks for reporting! Since the device still gets the notification this seems an issue with the OneSignal REST API. I transferred this issue there, the new URL for your issue is https://github.com/OneSignal/api/issues/27

Could you provide more details such as which platforms you are target (just `isAndroid`?) and which platforms you have enabled on the OneSignal dashboard? Can you also provide an example of the JSON you are sending in the POST /notifications request and the exact response you are getting?

**Comment by iojOMlyzI06b8nWnWfxI1BW** [comment]
Hello,
I did recieve invalid_external_user_ids responses yesterday
But I just test again and everything seem fine now
I don't know what is happening. But I think I will close this issue and hope it won't happen again
Thank you for supporting!
